// Atom
export const ATOM_AUTH_TOKEN = "ATOM_AUTH_TOKEN";
export const ATOM_SEARCH_ACCOUNT = "ATOM_SEARCH_ACCOUNT";

// React-Query
export const MUTATION_GENERATE_AUTH_TOKEN = "MUTATION_GENERATE_AUTH_TOKEN";
export const QUERY_ = "QUERY_";
export const QUERY_ASSET_HOLDERS = "QUERY_ASSET_HOLDERS";
export const QUERY_ACCOUNT_BALANCE = "QUERY_ACCOUNT_BALANCE";
export const QUERY_HOURLY_CONTRACT_ACTIVE_ACCOUNTS =
    "QUERY_HOURLY_CONTRACT_ACTIVE_ACCOUNTS";
export const QUERY_HOURLY_CONTRACT_TRANSACTIONS =
    "QUERY_HOURLY_CONTRACT_TRANSACTIONS";
